name: PR Continuous Integration

on:
  pull_request:
    branches:
      - master
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  # Build and test bazel targets #
  setup-bazel:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - macos
          - ubuntu
          - windows
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - if: failure() && runner.debug == '1'
        uses: mxschmitt/action-tmate@v3
      - name: Build all targets
        run: bazel build //...
      - name: Test all targets
        run: bazel build //...
  # Build and test bazel targets #

  # Test documentation deploy #
  test-docs-deploy:
    name: Test docs deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs/financial-trading
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: docs/financial-trading/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test build website
        run: yarn build
  # End test documentation deploy #
